-- MySQL Script generated by MySQL Workbench
-- 10/15/15 11:48:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL COMMENT '考试编号',
  `name` VARCHAR(500) NULL COMMENT '',
  `description` VARCHAR(2000) NULL COMMENT '',
  `start_time` DATETIME NULL COMMENT '',
  `end_time` DATETIME NULL COMMENT '',
  `duration` INT NULL COMMENT '考试时间',
  `is_published` TINYINT NULL COMMENT '0表示未分配；1表示已分配；',
  `is_result_published` TINYINT NULL COMMENT '',
  `attended_count` INT NULL COMMENT '',
  `examinee_count` INT NULL COMMENT '',
  `pass_rate` DOUBLE NULL COMMENT '系统通过率',
  `pass_score` DOUBLE NULL COMMENT '',
  `average` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '考试管理：对�' /* comment truncated */ /*�卷进行设置包括考试的开始 试卷、结束时间等*/;


-- -----------------------------------------------------
-- Table `mydb`.`examinee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examinee` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '用户的编号',
  `exam_id` INT NULL COMMENT '',
  `paper_id` INT NULL COMMENT '',
  `score` DOUBLE NULL COMMENT '',
  `attended_time` DATETIME NULL COMMENT '',
  `answered_count` INT NULL COMMENT '',
  `comment` VARCHAR(2000) NULL COMMENT '',
  `markers` VARCHAR(500) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_task_create_exam1` (`exam_id` ASC)  COMMENT '',
  CONSTRAINT `fk_task_create_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`map_examinee_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`map_examinee_answer` (
  `examinee_id` INT NOT NULL COMMENT '',
  `paper_question_id` INT NOT NULL COMMENT '问题编号',
  `score` DOUBLE NULL COMMENT '得分',
  `answer` VARCHAR(5000) NULL COMMENT '参与考试者的作答',
  `comment` VARCHAR(2000) NULL COMMENT '',
  `markers` VARCHAR(500) NULL COMMENT '',
  INDEX `fk_map_user_paper_question_map_user_exam1_idx` (`examinee_id` ASC)  COMMENT '',
  PRIMARY KEY (`examinee_id`, `paper_question_id`)  COMMENT '',
  CONSTRAINT `fk_map_user_paper_question_map_user_exam1`
    FOREIGN KEY (`examinee_id`)
    REFERENCES `mydb`.`examinee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '用户答题结果';


-- -----------------------------------------------------
-- Table `mydb`.`user_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_message` (
  `id` INT NOT NULL COMMENT '',
  `message_id` INT NOT NULL COMMENT '消息编号',
  `user_id` INT NULL COMMENT '接收消息的人',
  `title` VARCHAR(500) NULL COMMENT '',
  `type_id` INT NULL COMMENT '0:问题审核消息；1:任务分配消息；2:考试结果公布消息；3:系统消息',
  `received_time` DATETIME NULL COMMENT '',
  `url` VARCHAR(500) NULL COMMENT '',
  `from_user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '用户提交试卷题目的审核情况。';


-- -----------------------------------------------------
-- Table `mydb`.`map_paper_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`map_paper_exam` (
  `exam_id` INT NOT NULL COMMENT '',
  INDEX `fk_map_paper_exam_exam1_idx` (`exam_id` ASC)  COMMENT '',
  CONSTRAINT `fk_map_paper_exam_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marker` (
  `user_id` INT NOT NULL COMMENT '',
  `exam_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `exam_id`)  COMMENT '',
  INDEX `fk_map_grader_exam_exam1_idx` (`exam_id` ASC)  COMMENT '',
  CONSTRAINT `fk_map_grader_exam_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `mydb`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam_published_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam_published_type` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `value` DATETIME NULL COMMENT '',
  `refer_column` VARCHAR(45) NULL COMMENT '',
  `refer_table` VARCHAR(45) NULL COMMENT '',
  `refer_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message_type` (
  `id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `url` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `type_id` INT NULL COMMENT '',
  `entity_id` INT NULL COMMENT '',
  `created_time` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
